-- AlterTable
ALTER TABLE `Appointment` ADD COLUMN `notes` TEXT NULL,
    ADD COLUMN `service` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('AGENDADO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'AGENDADO';
